### ISSUE TITLE
Fix for crashing and notes

### ISSUE THREAD

**Issue by projectgheist** [Allar/ExportObjectPlugin#1]
I was able to fix the plugin from crashing my machine by forcing a garbage collection after every 10 frames (you could do this every frame), which you don't notice anyway. This is most likely due to the fact that normal garbage collection is done every 30 seconds and since the scene is captured every frame it creates too many textures which aren't cleaned up except during GC (but the game will most likely crash before that is even called).

Just a quick few notes:
- TextureRenderTargetCube doesn't rotate
- TextureRenderTargetCube doesn't capture postprocessing

Both of these require source code changes, which aren't possible in a plugin.

**Comment by Allar** [comment]
Another user pull requested some garbage collection functionality, that has now been merged in.

And aye, Epic is working on a more proper solution after hearing about this and a few other solutions, so hopefully they'll add in support themselves for rotation and post processing.

Thanks for the report!
