### ISSUE TITLE
How to use matinee to animate camera?

### ISSUE THREAD

**Issue by LionBrige** [Allar/ExportObjectPlugin#3]
Hi 
powerful plugins. 

I saw your demo, find the camera can be animated, but when I use matinee animated the camera, but no effect about this? Could you please tell me the right way to realize the result as your demo done?

**Comment by Allar** [comment]
Animating the camera is the same as animating any other object. Look up tutorials on how to use matinee and sequencer, and once you know enough to animate arbitrary objects, you can animate the camera the same way.
