### ISSUE TITLE
Exporting skips frames

### ISSUE THREAD

**Issue by hazem17** [Allar/ExportObjectPlugin#4]
Hi Allar, i'm using your plugin to export 360 video but it skips frames, i made sure that the frame rate is set to 30 in the project settings, then i read in forums that i must run the editor in benchmark mode, so i googled how to run in benchmark mode and i didn't find answers, can you tell me how to run the editor in benchmark mode, thanks

**Comment by Allar** [comment]
If you're capturing in editor, one way to kinda force it is to use t.overridefps 30 in console, combined with t.maxfps 30.
